#!/bin/bash

# define PROJ_HOME
PROJ_HOME="/home/thien/VNG/sre/icav2-api"

# define JAVA_HOME, depends on environment
JAVA_HOME="/usr/java/jdk1.8.0_121"

# define custom variables, different values from different projects
app_name=mto-wpvp2-ica-api
jar_file=dist/$app_name.jar
pid_file=tmp/$app_name.pid
appenv=local
apppath=$PROJ_HOME
console_log_file=/data/logs/mto-wpv2-ica/console.log
console_log_history=/data/logs/mto-wpv2-ica/console_history.log

cd $PROJ_HOME
export JAVA_HOME

function status {
    if ps -p $1 | grep $1 > /dev/null
    then
        return 0
    else
        return 1
    fi
}


function start {
    if [ -f $pid_file ]; then
        read pid <$pid_file
        if `status $pid`; then
            echo "Service is alredy running."
            return
        fi
    fi

    cat $console_log_file >> $console_log_history
    $JAVA_HOME/bin/java -cp lib \
    -Xmx2048M \
    -Duser.timezone=Asia/Ho_Chi_Minh \
    -Dfile.encoding=UTF-8 \
    -Dappname=$app_name \
    -Dapppath=$apppath \
    -Djava.library.path=/zserver/lib \
    -Dlog4j.configuration=file:./conf/$appenv.log4j.ini \
    -Dappenv=$appenv \
    -jar ./$jar_file 
    pid=$!
    if [[ -z  "$pid" ]]; then
        echo "Service failed to start. See log for more info."
    else
        echo "$pid" > $pid_file
        echo "Service has started. PID: $pid"
    fi
}

function stop {
    read pid <$pid_file
    if `status $pid`; then
        kill $pid
    else
        echo "Service is not running."
        return 1
    fi
    echo "Waiting for the service to finish stopping..."
    sleep 3
    while [ 1 ]
    do
        if ps -p $pid | grep $pid > /dev/null
        then
            sleep 1
        else
            break
        fi
    done
    return 0
}

case "$1" in
start)
start
;;
stop)
stop
;;
restart)
if stop; then
    start
fi
;;
status)
read pid <$pid_file
if `status $pid`; then
    echo "Service is running. PID: $pid"
else
    echo "Service is not running."
fi
;;
dump)
read pid <$pid_file
$JAVA_HOME/bin/jmap -histo:live $pid
;;
*)
echo "Usage: `basename $0` start|stop|restart|status|dump"
exit 1
esac

exit 0
